### ISSUE TITLE
Add TV Series

### ISSUE THREAD

**Issue by kolbdog3333** [theMK2k/Media-Hoarder#35]
Can you please make it so you can organize tv series episdoes as well not just movies thanks.

**Comment by theMK2k** [comment]
Hi @kolbdog3333,

yes, tv series support is on the road map.

**Comment by kolbdog3333** [comment]
Thanks wasnt sure i jsut installed it i like it so far but its annoying for tv shows since it only shows the epsidoe title that is why i asked.

**Comment by theMK2k** [comment]
Heh, ok, I didn't even test it that way. Yeah, stay tuned, it will still take a bit of time until the feature is available.

**Comment by kolbdog3333** [comment]
I sort them by tv series, season then the episode number and name all in separate folders up until the season folder
The format is Name of TV Show/Season Number/Episode Number - Name of Episode.

**Comment by theMK2k** [comment]
@kolbdog3333 the next days/weeks I'm working on series support. Would you be willing to beta-test as soon as I have something worthy to have a look at?

**Comment by kolbdog3333** [comment]
> @kolbdog3333 the next days/weeks I'm working on series support. Would you be willing to beta-test as soon as I have something worthy to have a look at?

Yes I would thanks for asking

**Comment by theMK2k** [comment]
@kolbdog3333 great! Which operating system do you use?

**Comment by kolbdog3333** [comment]
> @kolbdog3333 great! Which operating system do you use?

I use Windows 10.

**Comment by kolbdog3333** [comment]
I use windows 10 and am willing to help with the beta testing whenever you are ready.

**Comment by theMK2k** [comment]
Got it, I will let you know once a beta is out for you to test :)

**Comment by kolbdog3333** [comment]
Thank you. I appreciate all your hard work on this software.

**Comment by theMK2k** [comment]
@kolbdog3333 good news, you can grab a BETA pre-release here: https://github.com/theMK2k/Media-Hoarder/releases/tag/v1.3.37-a

To make use of TV series, provide source path/s in `Settings - Series` and run a re-scan of your media.

A new section "Series" will list your series and, after clicking the image of a series, its episodes.

Please use with caution! Probably start with a copy of some of your series and when feeling safe switch over to your main source path for series. You can also use the portable version of **Media Hoarder** if you don't want to update your stable version.

**Comment by theMK2k** [comment]
There's also some documentation linked in the release on how **Media Hoarder** expects the series source path to be organized. Re-reading what you stated on how you manage your TV series, it seems to match your schema.

**Comment by theMK2k** [comment]
Let's use this thread for further discussions and reports of your experiences with this new feature :)

I still have a lot to cover until it can be released as stable but I think we have a good start. I'm using the feature myself already ;)

**Comment by kolbdog3333** [comment]
I tried adding the pilot episode of Helluva Boss and it couldnt find it even with this format 
Helluva Boss
Season 1
S01E00 - Pilot 
I even tried adding the tt after the episdoe name still couldnt find it It thinks its the first episode Murder Family if i add the ttliink in the title
You might need to figure out ho wto do Season 1 episode 0 for some pilot episodes since it might not find them

**Comment by kolbdog3333** [comment]
I was just thinking maybe add something for Seasons like 
Season 1
Season 2 
Season 3 
excetra
That way if you want to watch a episdoe from a specific season you can click on the season and it will list all episdoes from that season or have the option to list them all together like it currently is doing depending on the format you want all the seasons for all the series in?

**Comment by kolbdog3333** [comment]
I also noticed sometimes the episodes are not in order like episode 2 might be after episode 1 dependign on the title since it sorts season episodes by title when you add them the seasons are kept in correct order but not the episode numbers i just tried it on one episode it added S2e1 the circus after season 2 episode 2 Seeing stars it added it in title order name not episode number.

**Comment by theMK2k** [comment]
**Pilot Episode**

Is any other episode properly recognized? Does the pilot show up in imdb.com at the series?

Yeah, the tt* at an episode is currently ignored. I'll see how to have it overrule the other series-episode detection handling.

**Comment by theMK2k** [comment]
**Sort Order**

Correct, I didn't touch sort orders in the Series section, so it's still the same as in Movies. This will definitely change (added "Season+Episode" item as default). That should fix the reported issue then.

I'm not sure about having selectable seasons. Let's see how the "Season+Episode" sort order will work out first.

**Comment by kolbdog3333** [comment]
Its only an episode that has 00 as an episode number it wont find it

**Comment by theMK2k** [comment]
Last release this year, I added an **a2** release to the assets here: https://github.com/theMK2k/Media-Hoarder/releases/tag/v1.3.37-a

v1.37.3-a2 fixes Episode 0 detection (just perform a re-scan of your media):

![image](https://github.com/theMK2k/Media-Hoarder/assets/16878526/f0bad7f3-4d4c-4e09-b9f8-be2a4b910afc)

and introduces "Season and Episode" sort order for the Series -> Episodes section. However, for now I keep the 20-items-per-page set up. You can still get a quick overview at which season/episode a page starts (see highlighted area in the screenshot).

![image](https://github.com/theMK2k/Media-Hoarder/assets/16878526/ff0a3c7d-1757-4af8-bcf9-64340e28a7fb)

**Comment by kolbdog3333** [comment]
I noticed if you add an episdoe that doesnt have a season and episode number like the ones that are in the unknown section of the episode list on the imbd website it won't add it will you fix that

**Comment by kolbdog3333** [comment]
Also i noticed if you remove an episode the episode number doesnt change where it says the amount of epiodes on the main page of the series

**Comment by theMK2k** [comment]
> I noticed if you add an episdoe that doesnt have a season and episode number like the ones that are in the unknown section of the episode list on the imbd website it won't add it will you fix that

Please provide an example for this (imdb link as well as directory and file names)

**Comment by theMK2k** [comment]
> Also i noticed if you remove an episode the episode number doesnt change where it says the amount of episodes on the main page of where all the series are located same with amount of seasons if its a season number

Well spotted, thanks!

**Comment by kolbdog3333** [comment]
Here is a link its for a spongebob series https://www.imdb.com/title/tt0206512/episodes/?season=Unknown
Here is how i have it in directory I have it as Unknown instead of actual season number since that is how it is on the website 
Spongebob Sqarepants(1999-)
Unknown
Twas the Night Before Spongemas

**Comment by kolbdog3333** [comment]
Maybe for the ones that are an unknown it can be labeled as specials and use the imdb tt next to the episode file namet o add it to fhe series like you use the tt for movies?

**Comment by kolbdog3333** [comment]
Since the episode isn't really a episode for that series its a t.v. special  that has no season or episode number

**Comment by kolbdog3333** [comment]
Also maybe add something to check for duplicates so it won't add 2 of the same Episode by mistake since I had that happen once if the episode name is different bur season and episode was the same it added both so there were two copies of same episode when their only should be one

**Comment by kolbdog3333** [comment]
Was thinking maybe add tvdb, tmdb or omdb something like one of those for an additonal scraper in case IMDB doesnt have the tv show listed or can't find it like for example Looney Tunes that is a series even though there are a lot of shorts you shouldnt need to add it to the movies section since those aren't movies same with Popeye and all the old classic cartoons?

**Comment by theMK2k** [comment]
> Was thinking maybe add tvdb, tmdb or omdb something like one of those for an additonal scraper in case IMDB doesnt have the tv show listed or can't find it like for example Looney Tunes that is a series even though there are a lot of shorts you shouldnt need to add it to the movies section since those aren't movies same with Popeye and all the old classic cartoons?

Yeah let's see, that would be a larger project.

**Comment by kolbdog3333** [comment]
Okay thanks anyways thought would ask.

**Comment by theMK2k** [comment]
> Here is a link its for a spongebob series https://www.imdb.com/title/tt0206512/episodes/?season=Unknown Here is how i have it in directory I have it as Unknown instead of actual season number since that is how it is on the website SpongeBob SquarePants(1999-) Unknown Twas the Night Before Spongemas

I'm working on multiple solutions for this.

The tt* being explicitly stated in the filename is one of these.

Another one is an implementation of the "link to imdb" dialog which is already available but not properly adjusted to series use-cases.

Lastly, if an episode does not provide a season+episode number, getting the correct imdb data could be mamaged by comparing the filename and the imdb titles, given the filename contains such a title, e.g. the Spongebob Christmas special mentioned by you.

**Comment by kolbdog3333** [comment]
What about that formatting i showed for Doctor who tv series for example would that work and so when the show is added to the series its labeled as Special then name of episode?

**Comment by theMK2k** [comment]
> What about that formatting i showed for Doctor who tv series for example would that work and so when the show is added to the series its labeled as Special then name of episode?

Yes, that would totally work as soon as the tt* override is properly in place. I need to get my head around how to organize non-season stuff in Media Hoarder. "Specials" unfortunately also starts with an "S", so that doesn't differentiate enough from seasons as soon as it needs abbreviation.

I saw somewhere (other media frontend) that they just put anything under S00. IMDB uses "Unknown"...

**Comment by theMK2k** [comment]
Maybe just everything non-season as "Bonus, Extras, Specials" and abbreviate that with "B". Something like that.

Maybe it also makes sense to differentiate bonus, extras and specials...

**Comment by theMK2k** [comment]
In the next update, Media Hoarder will also have an enhanced "Edit Media" dialog where you can specify season number, episode number or bonus/extra/special.

**Comment by theMK2k** [comment]
> That works also how will you deal with Looney Tunes, Popeye, Betty Boop, Tom and Jerry stuff like that since those aren't movies i dont want to put those in the movie section those are old cartoons and are tv series?

No problem there. Media Hoarder treats anything inside a first-order directory in a source-path as "one series". So organization-wise we're set. For the data of the episodes which may not be actual episodes of a particular series, we will find a solution as soon as the tt* override / updated "link imdb" dialog is implemented.

**Comment by kolbdog3333** [comment]
Since be useful if you add Looney tunes or any standalone tv series that isnt part of an actual "series" on imdb.

**Comment by kolbdog3333** [comment]
Maybe make it so when you click the go back button when in one of the tv series  it can take you to last page you were on example page 2 instead of it taking you to the first main page each time?

**Comment by kolbdog3333** [comment]
I iknow this isn't a tv series issue but i was thinking for the mediai nfo check instead of it opening everytime you do a rescan for every item it only opens on movies or series you havent added yet instead of it checking every single item in the media hoarder library.

**Comment by theMK2k** [comment]
Yeah, could you please open up a new issue in here? It's getting a bit overwhelming - even with all the other parallel series topics.

**Comment by kolbdog3333** [comment]
Sorry

**Comment by theMK2k** [comment]
I just added v1.3.37-a3 to the BETA releases here: https://github.com/theMK2k/Media-Hoarder/releases/tag/v1.3.37-a

It now does do the tt* override, given a tt* is detected in the media's file name. With that, we're one step closer to the Looney Tunes use-case:

![image](https://github.com/theMK2k/Media-Hoarder/assets/16878526/cb8b472b-b485-46da-8cd4-5a91b2aadd06)

**Comment by kolbdog3333** [comment]
What has been changed or fixed in version 1.3.3-7a?  Maybe you should put what's been added on the release page so people know what's been changed or fixed for each beta release?

**Comment by kolbdog3333** [comment]
So how does a tt* override work?

**Comment by kolbdog3333** [comment]
Maybe for custom series for folders you can do this
Popeye (TV Series)
Looney Tunes (Tv Series)

So when it scans the folders if it has tv series in ( ) it will know its not a series on imdb but a custom series so you can add your own poster from an image since on media hoarder it won't be blank in the tv section the picture.

**Comment by theMK2k** [comment]
> So how does a tt* override work? Also be useful for other series not just Looney Tunes like Tom and Jerry, Popeye, Betty Boop, excetra all the old classics.

Sorry, yes, the tt* override means: you provide the tt* IMDB ID in the filename and Media Hoarder does not try to find the IMDB data by season and episode numbers but with the explicitly provided tt* IMDB ID.

I just dubbed this the "Looney Tunes use-case" and of course it can be applied to more series.

**Comment by theMK2k** [comment]
> Maybe for custom series for folders you can do this Popeye (TV Series) Looney Tunes (Tv Series)
> 
> So when it scans the folders if it has tv series in ( ) it will know its not a series on imdb but a custom series so you can add your own poster from an image since on media hoarder it won't be blank in the tv section for the picture.

That's too much magic. Yeah, in these cases Media Hoarder might link to wrong IMDB data but that can be unlinked afterwards by the user:

![image](https://github.com/theMK2k/Media-Hoarder/assets/16878526/c96864d7-853a-441f-bc23-df0a3ea410fa)

![image](https://github.com/theMK2k/Media-Hoarder/assets/16878526/2e34e496-182e-4c3e-8865-08da86447089)

Providing a user-defined poster is currently not there yet, but it's on the road map.

**Comment by theMK2k** [comment]
> page

I just added **v1.3.37-a4** which tackles this issue. Media Hoarder now saves the last page of the Movies, Series and each series' Episodes section. It loads that page number right after the media is loaded. So when you press the back button and return to the Series section, it should be at the page you left off.

**Comment by kolbdog3333** [comment]
I was just thinking maybe for two part episodes that are 25 minutes like cartoons where it shows for example S1.1 Cloned/Feeling Alive as the episode name. 
And you only have half the episode that is 10 min for example Feeling Alive. You can put in the file name S01E01b since its same episode just not the full episode and it will still identify it as the full episode them you can rename it as the half of thr Episode you want and change the summary and then when you have S01E01b it will still detect it as the same episode but it's a different file name ans you can do the same thing.

**Comment by theMK2k** [comment]
I extracted multiple issues raised in here to individual threads, so they can be tracked better. Closing this one now.
