### ISSUE TITLE
Downlaod movies from chatgpt recomondations using imdb and yt-dlp

### ISSUE THREAD

**Issue by kolbdog3333** [theMK2k/Media-Hoarder#38]
Maybe you can make it so when you do the chatgpt suggestion for list of movies and it adds it to your library you can use yt-dlp and a search feature to download the full movie into your Movie location stored in settings so you can play the movie for free after chatgpt and media hoarder adds it to library same with tv shows like how justwatch.com shows the free movie so can download it. Sorry for the rambling.
Example:
1. The Hunger Games: Mockingjay - Part 2 (https://www.imdb.com/title/tt1951266/?ref_=sr_t_1)
2. Deadpool (https://www.imdb.com/title/tt1431045/?ref_=sr_t_2)
3. Suicide Squad](https://www.imdb.com/title/tt1386697/?ref_=sr_t_3)
4. The Nice Guys](https://www.imdb.com/title/tt3799694/?ref_=sr_t_4)
5. Rogue One: A Star Wars Story](https://www.imdb.com/title/tt3748528/?ref_=sr_t_5)
6. The Magnificent Seven](https://www.imdb.com/title/tt2404435/?ref_=sr_t_6)
7. Shin Godzilla](https://www.imdb.com/title/tt4262980/?ref_=sr_t_7)
8. The Revenant](https://www.imdb.com/title/tt1663202/?ref_=sr_t_8)
9.  Kong: Skull Island (https://www.imdb.com/title/tt3731562/?ref_=sr_t_9)

Then after it shows the Movie recomondation it will search the internet for free version of the movie you wish download after you select which movie you want to add to your library and then it will add the movie and download it if it can find a free version of the movie using yt-dlp

Sorry for the long post is just a suggestion for the ai movie recommendations.

**Comment by kolbdog3333** [comment]
If can't do it or don't like the suggestion don't worry about it you can just close this.

**Comment by theMK2k** [comment]
I see what you mean but I have to give that a hard pass as this would be illegal in many regions of the world. Media Hoarder should only work with what you already have, sorry.
