### ISSUE TITLE
Multipart Episodes

### ISSUE THREAD

**Issue by theMK2k** [theMK2k/Media-Hoarder#39]
> I was just thinking maybe for two part episodes that are 25 minutes like cartoons where it shows for example S1.1 Cloned/Feeling Alive as the episode name. 
And you only have half the episode that is 10 min for example Feeling Alive. You can put in the file name S01E01b since its same episode just not the full episode and it will still identify it as the full episode them you can rename it as the half of thr Episode you want and change the summary and then when you have S01E01a it will still detect it as the same episode but it's a different file name ans you can do the same thing.

_Originally posted by @kolbdog3333 in https://github.com/theMK2k/Media-Hoarder/issues/35#issuecomment-1882208253_

**Comment by kolbdog3333** [comment]
I was thinking maybe if you add the actual episode name to file name to when imdb scrapes the episodes  you can do the multipart episode you can do same episode example S01E01 - The Big Blow Out. Will still crape the episode but if you change episdoe name in file namiong to S01E01 - The big blow out. You can have two of teh same epsidoe then you can rename the episode and change summary manually? So it still adds the same episode twice i think that might solve the problem easier. Like check for filename or something like that.

**Comment by kolbdog3333** [comment]
That way in the folder you can have two S01E01 with two different file names am not sure if you can do this already but just idea

**Comment by theMK2k** [comment]
duplicate of https://github.com/theMK2k/Media-Hoarder/issues/74

if not, feel free to re-open
