### ISSUE TITLE
Series: Organization of Extras / Specials / Bonus

### ISSUE THREAD

**Issue by theMK2k** [theMK2k/Media-Hoarder#41]
> What about that formatting i showed for Doctor who tv series for example would that work and so when the show is added to the series its labeled as Special then name of episode?

> Yes, that would totally work as soon as the tt* override is properly in place. I need to get my head around how to organize non-season stuff in Media Hoarder. "Specials" unfortunately also starts with an "S", so that doesn't differentiate enough from seasons as soon as it needs abbreviation.

> I saw somewhere (other media frontend) that they just put anything under S00. IMDB uses "Unknown"...

> Maybe just everything non-season as "Bonus, Extras, Specials" and abbreviate that with "B". Something like that.

> Maybe it also makes sense to differentiate bonus, extras and specials...

_Originally posted by @kolbdog3333 @theMK2k in https://github.com/theMK2k/Media-Hoarder/issues/35#issuecomment-1874052956_

**Comment by kolbdog3333** [comment]
What about episodes that don't have episode numbers like this for example for the show Mighty Magiswords
https://www.imdb.com/title/tt5078610/
The episode is an episode but doesnt have an episode number Maybe for those you can do this for imdb scraping 
S0E00 - No Robots for Old Men since its still an episode but doesnt have an official season or episode number but it will still scrape the show Mighty Magiswords for example to find the episode and those type of episdoes will be placed first and those episodes in Media hoarder can be formated like this  S00.E00 No Robots for Old Men (2015) for example. Just an idea to help  with unknown episodes if you think that would work.

**Comment by theMK2k** [comment]
In another issue (#55) we already discovered that S00E00 would work. If you have multiple officially unnumbered episodes, it would be helpful to actually number them in their filenames, so that the episodes overview doesn't break.

Scraping is another thing. Media Hoarder, as of v1.4.0-b3 cannot find the correct IMDB entry for an episode without a proper season and episode numbering, let alone a differently applied one (e.g. S00E01) yet. There will be an update to the scraper in the future, but this is out of scope for this issue.

For the rest, we'll stick to B* for Bonus/Special/Extra. I'll keep the issue open as there might be some additional work to be done in order to support that and which I'll start working on now ;)

**Comment by theMK2k** [comment]
@kolbdog323 do you happen to know a series where bonus episodes can clearly be attributed to certain seasons?

For example a series as two bonus episodes in season 3 and the names of the episodes are "a christmas special" and "a halloween special".

Interesting would be that these bonus episodes don't have a dedicated episode number on IMDB.

**Comment by kolbdog323** [comment]
Look at a series and then look at the unknown section thsoe are considered bonuses or not part of the main series. Example Mighty Magiswords it has a whole bunch of Unknown episodes on imdb and Helluva Boss on Imdb has one unkown epiosde.

**Comment by kolbdog323** [comment]
Maybe for those do the order it appears on imdb in the unknown section example S00BE01. For first one on the list?

**Comment by kolbdog323** [comment]
Sorry meant S00B001.

**Comment by kolbdog323** [comment]
Maybe the show Doctor Who (2009) will have some.

**Comment by kolbdog323** [comment]
Yep it defiintely does the Doctor Who (2005-2002) series has about 20 episodes like that.

**Comment by theMK2k** [comment]
Thanks, I'll have a look.

**Comment by kolbdog323** [comment]
Maybe for extra episodes that aren't related to a season do B00E01 for Bonus Season 0 Episode 1? or S00BE01? For Season 0 Bonus Extra Episode 1?

**Comment by theMK2k** [comment]
Doctor Who is spot on. Found an example:

"The Day of the Doctor" https://www.imdb.com/title/tt2779318/
IMDB lists this as Unknown Season but some sources say it's the 15th episode of season 7. So this one can be `Doctor Who - The Day of the Doctor S07B01` in some collections.

**Comment by theMK2k** [comment]
> Maybe for extra episodes that aren't related to a season do B00E01 for Bonus Season 0 Episode 1? or S00BE01? For Season 0 Bonus Extra Episode 1?

I wouldn't treat Bonus as a season of its own, so `B00E01` is out of the question.

We're left with:

either the bonus can be attributed to a season, then you have `S03B01`

or

the bonus can't be attributed to a season, then you have `S00B01`

**Comment by kolbdog323** [comment]
Why not do both?  And then the season S03B01 would move to where that seasons if part of a season where the official season episodes are located the non non official season episodes would be directly above season 01?

**Comment by theMK2k** [comment]
sorry, I wasn't clear with my "either ... or", of course I mean both are then possible

**Comment by theMK2k** [comment]
organization of extras / specials / bonus is implemented with the latest beta
