### ISSUE TITLE
Missing trailer url on IMDB Check

### ISSUE THREAD

**Issue by kolbdog3333** [theMK2k/Media-Hoarder#43]
It looks like IMDB changed the trailer because i got a $IMDB_Trailer_URL_missing when i tried to do the scan check.

**Comment by theMK2k** [comment]
Thanks for letting me know. The IMDB check is also a constant check which notifies me by email daily as soon as a problem arises.

I think I might have a chance to take a look this weekend or Monday.

I'll keep this issue open until a fix is ready.

**Comment by theMK2k** [comment]
This issue resolved on its own. Great :)
