### ISSUE TITLE
Not grabbing IMDB scrape page half the time

### ISSUE THREAD

**Issue by kolbdog3333** [theMK2k/Media-Hoarder#44]
For some reason when it is  scanning imdb episodes half the time the metadata and all the information was not scraped. It is able to get the TV Series main page but none of the episodes I even did a manual rescrape after it added the series it still dint add anything.

**Comment by kolbdog3333** [comment]
It seems whenever i redo the media scrape always a problem it even says: query 'Blue Season 2' results missing. For some reason that error is causing it not to scrape the IMDB page half the time i even uninstalled the media hoarder and deleted the media hoarder portbale version and the error still appears not sure how to fix that error if that error wasn't there it probably would fix Media Hoarder scraping the page..

**Comment by theMK2k** [comment]
Could you provide an IMDB link to the series in question?

**Comment by kolbdog3333** [comment]
Can't it's all my series it stops after a certain part in the collection then stops scrapping then it just does adding media info adding metadata and it just keeps going.

**Comment by kolbdog3333** [comment]
The same error query 'Blue Season 2' results missing and that is causing all the shows no longer to scrape. Here is the imdb link to series if think will help:
https://www.imdb.com/title/tt7678620/

**Comment by kolbdog3333** [comment]
Until this gets fixed i switched over to Kodi for time being.

**Comment by theMK2k** [comment]
> Until this gets fixed i switched over to Kodi for time being.

We're still in Beta and this at least for the next weeks and months for the series feature. While your help in identifying issues is appreciated, the comment above isn't helpful :/

**Comment by kolbdog3333** [comment]
Sorry will delete it

**Comment by theMK2k** [comment]
No need for deletion :)

**Comment by theMK2k** [comment]
Back to the topic at hand:

So every time the scanning is broken at or after Bluey Season 2. Interesting, I already have a test set of 1700 series with 100k episodes (all are just 0-byte files) in order to test the scanning. I haven't seen such an issue yet.

**Comment by kolbdog3333** [comment]
I felt like jerk since you are trying your best that is why deleted the comment

**Comment by kolbdog3333** [comment]
Not sure why its doing it for me it happens every time i even deleted media hoarder and reinstalled it same issue.

**Comment by theMK2k** [comment]
> I felt like jerk since you are trying your best that is why deleted the comment

It's ok as I also understand the frustrations of a Beta tester more now :)

**Comment by theMK2k** [comment]
> Not sure why its doing it for me it happens every time i even deleted media hoarder and reinstalled it same issue.

Yeah, this shows that it is a re-occuring issue - which is actually good.

**Comment by kolbdog3333** [comment]
Also it happened in portable version as well. I even tried deleting my entire library and do a fresh imdb scrape check same problem.

**Comment by theMK2k** [comment]
I'll now try to narrow it down by testing with a series source path with Bluey and another series. Let's see.

**Comment by theMK2k** [comment]
Found the culprit, will create an update.

**Comment by kolbdog3333** [comment]
Thank you appreciate it

**Comment by theMK2k** [comment]
**v1.3.37-a5** is added to https://github.com/theMK2k/Media-Hoarder/releases/tag/v1.3.37-a

**Comment by theMK2k** [comment]
and once again IMDB scraper needed an update, -a6 is uploaded to the BETA releases (see link above)

**Comment by kolbdog3333** [comment]
Looks like the new version brought back the bluey query 'Bluey Season 2' results missing for some reason

**Comment by kolbdog3333** [comment]
Since with that can't scan any metatadata for episodes with that imdb erorr and rescan manually dosnt work either i have to manually link each episode

**Comment by theMK2k** [comment]
You can always install an older version. Of course I'll have a closer look in the next hours.

**Comment by kolbdog3333** [comment]
I tried there is even more imdb missing in the scraper 
![Uploading Untitled.png…]()
then the newer version Here is the attatchment

**Comment by kolbdog3333** [comment]
![Untitled](https://github.com/theMK2k/Media-Hoarder/assets/75857608/553c2418-2a27-4dca-b4ab-95a65d0ba88b)

**Comment by kolbdog3333** [comment]
As you can see i reinstalled older version and there was more scraping data missing then the newer version

**Comment by theMK2k** [comment]
> As you can see i reinstalled older version and there was more scraping data missing then the newer version

Yes, that's why -a6 has been created in the first place. That series issue might have slipped through and will be fixed with -a7 coming up shortly.

**Comment by kolbdog3333** [comment]
Thank you again. Since its very annoying having to do every episode of every tv show manually using link and copying the imdb tt(id) and grabbing the metadata that way same with some tv shows as well not just episodes.

**Comment by kolbdog3333** [comment]
Thank you again. Since its very annoying having to do every episode of every tv show manually using link and copying the imdb tt(id) and grabbing the metadata that way same with some tv shows as well not just episodes.

**Comment by theMK2k** [comment]
OK, I just installed v1.3.37-a6 and the imdb scraper test page looks good:

![image](https://github.com/theMK2k/Media-Hoarder/assets/16878526/e51ee4b6-e58b-4603-93cc-feaf167a6a33)

**Comment by theMK2k** [comment]
> Thank you again. Since its very annoying having to do every episode of every tv show manually using link and copying the imdb tt(id) and grabbing the metadata that way same with some tv shows as well not just episodes.

Yeah, this is not supposed to be of course. Media Hoarder should:

- find the correct series by the series directory name (a tt* is definitely helpful there)
- find the episode according to the series by utilizing the season and episode numbers of the episode's filename (a manual linking or per-episode tt* should only be necessary in very few edge cases)

Now, at least on my end, the scraper tests look good with v1.3.37-a6 (the version uploaded today). Is this still not the case on your end?

**Comment by kolbdog3333** [comment]
Working again after i deleted everthing in the Media hoarder program folder it started working again after reinstalling it.

**Comment by theMK2k** [comment]
> Working again after i deleted everthing in the Media hoarder program folder it started working again after reinstalling it.

Great to hear!

**Comment by kolbdog3333** [comment]
> > Working again after i deleted everthing in the Media hoarder program folder it started working again after reinstalling it.
> 
> Great to hear!

For some reaason i can't uninstall it normally as shown in my other issue

**Comment by kolbdog3333** [comment]
It was gone now the error is back query 'Bluey Season 2' results missing i dont know why i didnt even add any of those videos to my library this time

**Comment by theMK2k** [comment]
I see, -a7 is on the way :)

**Comment by theMK2k** [comment]
v1.3.37-a7 is uploaded to https://github.com/theMK2k/Media-Hoarder/releases/tag/v1.3.37-a

(the older versions are removed)

**Comment by kolbdog3333** [comment]
Weird scraping error for plot summary here it is but you can still scrape shows with no problem same with series.

$IMDB_plotSummaryFull mismatch got: "In occupied France, an elderly man and his niece are forced to give shelter to a German army lieutenant who seemingly loves their country and culture." expected: "1941 in a small town in Nazi occupied France. Against the will of its elderly male and his adult niece residents, the Nazis commandeer a house for one of their officers, Lt. Werner von Ebrennac, to live in for as long as he is in the area on Nazi business. As a figurative and literal silent protest against the Nazis and the officer, the uncle and niece do whatever is required of them while the officer is in their house, however they do not acknowledge his presence, living largely in silence whenever he is around. The officer treats the housing situation with care, like he is a guest. Although not a nightly occurrence, the officer begins an evening routine with his reluctant hosts: in his civilian clothes, he knocks on the door of the room in which they have convened for the evening, walking in shortly thereafter knowing that no acknowledgment will be made for him to enter, he visits with them for no more than five minutes before he bids them a good evening as he exits. During these visits, he speaks reverently about, among other things, culture - music and literature in particular as he is a composer and musician - his national pride, his love of France, and what he hopes will emerge from the war, namely a strong and free France, stronger than it was before the war, and the marriage between the French and German cultures which will enrich the lives of all Europeans. All the while, he makes no expectations from them, either to listen, or to answer if they are indeed listening. At the end of what ends up being his six month stay at the house, he does end up having a profound effect on the uncle and niece, despite that effect being largely unacknowledged, as his stay in France has a profound effect on him, opening up his eyes to the reality of the war based largely on his first ever visit into Paris."

**Comment by kolbdog3333** [comment]
Also another error:

Advanced Title Search (Ad-Hoc)
query 'FoRReST GuMp' [] results missing

No idea where this came from I dont even watch that movie.

**Comment by theMK2k** [comment]
@kolbdog3333 Just to clarify and this is also stated in the IMDB Scraper Test Dialog: The imdb.com web scraper is **tested** using a **test-set of example data**.

The example data mentioned here is predefined by Media Hoarder and won't necessarily match what you actually have. This way Media Hoarder can **compare** an **expected result** against what it **actually receives by accessing IMDB**.

I could hide the specific error/warning details to reduce confusion, however, when a user reports an issue, the details actually help in fixing the issue.

**Comment by theMK2k** [comment]
All IMDB scraper issues are fixed with v1.3.4 (stable) and v1.3.37-a8 (BETA).

Download the v1.3.4 (stable) via <https://media.hoarder.software/downloads>

Download v1.3.37-a8 (BETA):

<https://downloads.hoarder.software/media-hoarder-1.3.37-a8-win-x64-setup.exe>
<https://downloads.hoarder.software/media-hoarder-1.3.4-win-x64-portable.zip>
<https://downloads.hoarder.software/media-hoarder-1.3.37-a8-win-x64-setup.exe.sha256>
<https://downloads.hoarder.software/media-hoarder-1.3.4-win-x64-portable.zip.sha256>

**Comment by theMK2k** [comment]
closing this (IMDB scraper is fine now), if anything similar arises, please open a new ticket.
