### ISSUE TITLE
More than one Season 0 wrong season and episdoe order

### ISSUE THREAD

**Issue by kolbdog3333** [theMK2k/Media-Hoarder#49]
It seems if you have more than one Season 0 episode in the series it makes the entire season and episode order go out of wack. Here is a pic to show you what I mean.
![error](https://github.com/theMK2k/Media-Hoarder/assets/75857608/6adca56b-a499-4400-bd2f-bffb11d7f4a3)

**Comment by kolbdog3333** [comment]
Also hen you remove the episodes that are wrong the episodes remain in wrong order even after reloading the page

**Comment by theMK2k** [comment]
OK, wrong order is already covered by https://github.com/theMK2k/Media-Hoarder/issues/50, let's fix that first :)

**Comment by kolbdog3333** [comment]
Also this problem caused imdb to no longer scrape season 0 episodes if they are on imdb.

**Comment by kolbdog3333** [comment]
Since found way to add some shows and episodes if have no proper episode number or season number.

**Comment by theMK2k** [comment]
> Also this problem caused imdb to no longer scrape season 0 episodes if they are on imdb.

Could you please create a new issue for this? Also provide the imdb id and the filenames.

**Comment by theMK2k** [comment]
> Since found way to add some shows and episodes if have no proper episode number or season number.

I can't make much sense out of what you wrote here, sounds to me like a different topic, so, please create a new issue, thanks :)

**Comment by kolbdog3333** [comment]
> > Since found way to add some shows and episodes if have no proper episode number or season number.
> 
> I can't make much sense out of what you wrote here, sounds to me like a different topic, so, please create a new issue, thanks :)

Not issue just found work around for tv shows example Looney tunes, Popeye stuff like that that  and episodes that don't have proper season number or episode or if don't exist.

Also the season 0 not scraping was caused by the issue mentioned earlier in this post whsn that happened season 0 no longer scraped

**Comment by kolbdog3333** [comment]
So the season 0 not scraping for any show and this one are linked together.

**Comment by theMK2k** [comment]
@kolbdog3333 please test with v1.3.37-a8 if the origin of this ticket is resolved.

Any other topic brought up in here, if not already covered by another issue/ticket, deserves a new ticket.

**Comment by theMK2k** [comment]
@kolbdog3333 is this issue resolved?

**Comment by kolbdog3333** [comment]
The wrong order got resolved am not sure about the season 0 yet but the wrong order sorted itself out. I will test it in a second.

> @kolbdog3333 is this issue resolved?

**Comment by kolbdog3333** [comment]
I think its fixed i'll let you iknow if any issues later this week if it happens again.
