### ISSUE TITLE
No longer correct Order

### ISSUE THREAD

**Issue by kolbdog3333** [theMK2k/Media-Hoarder#50]
It seems that every show is no longer sorting by season and episode number even with Series and Episode and sort chosen. It just adds the newest episode on top and wont sort them anymore. Even reload doesnt work,.

**Comment by theMK2k** [comment]
Thanks, I'll have a look.

**Comment by theMK2k** [comment]
Found the culprit, -a8 is ready, unfortunately github currently has issues when trying to upload a file to the releases section, stay tuned.

**Comment by theMK2k** [comment]
Github still doesn't allow me to reliably upload binaries.

You can get v1.3.37-a8 here:

<https://downloads.hoarder.software/media-hoarder-1.3.37-a8-win-x64-setup.exe>
<https://downloads.hoarder.software/media-hoarder-1.3.4-win-x64-portable.zip>
<https://downloads.hoarder.software/media-hoarder-1.3.37-a8-win-x64-setup.exe.sha256>
<https://downloads.hoarder.software/media-hoarder-1.3.4-win-x64-portable.zip.sha256>

Please test with that version and let me know if it works your end.

**Comment by kolbdog3333** [comment]
What was all fixed?

**Comment by theMK2k** [comment]
> What was all fixed?

The issue with ordering reported in this ticket.

**Comment by theMK2k** [comment]
@kolbdog3333 is this issue resolved?

**Comment by theMK2k** [comment]
closing this, as it should've been solved by -a8
