### ISSUE TITLE
Found work around for custom shows and episodes

### ISSUE THREAD

**Issue by kolbdog3333** [theMK2k/Media-Hoarder#51]
> > Since found way to add some shows and episodes if have no proper episode number or season number.
> 
> I can't make much sense out of what you wrote here, sounds to me like a different topic, so, please create a new issue, thanks :)

Not issue just found work around for tv shows example Looney tunes, Popeye stuff like that that  and episodes that don't have proper season number or episode or if don't exist.

Also the season 0 not scraping was caused by the issue mentioned earlier in this post whsn that happened season 0 no longer scraped

_Originally posted by @kolbdog3333 in https://github.com/theMK2k/Media-Hoarder/issues/49#issuecomment-1937849636_

**Comment by theMK2k** [comment]
@kolbdog3333 @kolbdog323 with this, do you mean you found a work around? If yes, would you tell more about it?

**Comment by kolbdog323** [comment]
If you add a show then put the tt bindng you can make it so it will use that for the tv show example for three stooges there arent any shwos for example three stooges but there are movies you can use that in the tv series. Then use the S01E01 like usaul then add the tt binding for that episode or short for looneyh toones or three stooges stuff like that.

**Comment by theMK2k** [comment]
Understood. But this won't give you a poster for the series, right? Because the "made-up" episodes (each having the tt* link to an IMDB entry) will cover the episodes but the series is missing an IMDB entry entirely, correct?

**Comment by kolbdog323** [comment]
it gives you the poster of the movie your using for series same with summary but you can manually edit both the summar and title it uses the tt binding..

**Comment by theMK2k** [comment]
nothing to do implementation-wise, please re-open this issue if otherwise
