### ISSUE TITLE
Question: Add to Lists

### ISSUE THREAD

**Issue by kolbdog3333** [theMK2k/Media-Hoarder#54]
How do you add to the lists in movie or series? I am not sure if you have that posted on here how to do that or not. Be nice so can organize some of my movies into a list or a episodes i want to watch so can just go to the list.

**Comment by theMK2k** [comment]
Looks like I haven't.

To define or add to a list, just expand the movie or series item by clicking anywhere that is not explicitly clickable:

![image](https://github.com/theMK2k/Media-Hoarder/assets/16878526/100f88bf-3cc7-4b10-a8e1-ad45b8f8c34f)

Then click the "Add" button in the "In Lists" section. A dialog appears where you can either create a new list or assign the item to an existing list:

![Uploading image.png…]()

**Comment by theMK2k** [comment]
@kolbdog3333 however, currently you can only filter lists in Movies and Series but not Episodes (episodes don't provide filter at all), this will be updated in the future.

**Comment by kolbdog3333** [comment]
> @kolbdog3333 however, currently you can only filter lists in Movies and Series but not Episodes (episodes don't provide filter at all), this will be updated in the future.

Thank you I wasn't sure..
