### ISSUE TITLE
Wont add season or episode number to main seires page

### ISSUE THREAD

**Issue by kolbdog3333** [theMK2k/Media-Hoarder#55]
Sorry wasn't sure how to word that but it seems if you add a episode into a series that doesnt have a official season or episode it wont update the amount of seasons or episdoes in the series.
For example i just add Raven's Tale: The Story of a Rebel in the Ever after High Series usign the ttid since it doesnt ahve a official season or episode but it wont update into the main page that its a season or episdoe even though on the website its in teh unkown tab Here is a link to the season page:
https://www.imdb.com/title/tt3312378/episodes/?season=Unknown
Here is a pic of my series so you can see the issue i am tlaking about and if i even have it labeled as 
![Untitled](https://github.com/theMK2k/Media-Hoarder/assets/75857608/32f9532e-934d-403d-9b4e-c2354a6ecd32)

**Comment by theMK2k** [comment]
thanks for the report, I'll investigate

**Comment by theMK2k** [comment]
@kolbdog3333 @kolbdog323 The Unknown category is ambiguous. There can be actual episodes but also bonus bits and extras in there. Should we count all those as episodes even though we don't really know if that's the case?

**Comment by theMK2k** [comment]
Remark: imdb.com actually does count each item in the Unknown category as an episode

**Comment by kolbdog323** [comment]
> Remark: imdb.com actually does count each item in the Unknown category as an episode

Maybe just label those as S0 for when you have it scan them since Unkown is a sesaon but its an unkonwn season? So basically it would be Season 0 instead? So example if you do an episode it would be S00E01 since its not an actual season number?

**Comment by theMK2k** [comment]
I just tested this by creating the following files and directories:

```
z:\_TESTSPACE\Media-Hoarder\Series\Ever After High\                                                                                                 0   09.04.2024  18:59.36  ----
  z:\_TESTSPACE\Media-Hoarder\Series\Ever After High\Season00\                                                                                      0   09.04.2024  19:01.19  ----
    z:\_TESTSPACE\Media-Hoarder\Series\Ever After High\Season00\Ever After High S00E00 - Apple's Tale - The Story of a Royal [tt5427958].mkv        0   09.04.2024  18:59.57  -a--
    z:\_TESTSPACE\Media-Hoarder\Series\Ever After High\Season00\Ever After High S00E00 - Raven's Tale - The Story of a Rebel [tt5251118].mkv        0   09.04.2024  19:00.21  -a--
    z:\_TESTSPACE\Media-Hoarder\Series\Ever After High\Season00\Ever After High S00E00 - The World of Ever After High [tt4190500].mkv               0   09.04.2024  19:00.38  -a--
```

And the result after scanning looks good:

![image](https://github.com/theMK2k/Media-Hoarder/assets/16878526/2a7f29ec-e7d3-468e-9269-2c0b46a4d73d)

**Comment by theMK2k** [comment]
having them be all S00E00 breaks the episodes overview, though:

![image](https://github.com/theMK2k/Media-Hoarder/assets/16878526/c36a6361-99fc-4875-8968-3460f8466fda)

so yeah, maybe episode numbers should still be in increasing sequence in the file names

**Comment by theMK2k** [comment]
The solution for this issue: please help Media Hoarder a bit by providing S00E01 etc. as well as the IMDB tt* number to each file name that you like to be treated as an episode (and should be counted towards the total number of episodes).

Later, Media Hoarder might be able to detect the correct episode's imdb entry but currently - for the Unknown category - Media Hoarder needs the tt* number.
