### ISSUE TITLE
Add TMDB incase missing episode or movie

### ISSUE THREAD

**Issue by kolbdog323** [theMK2k/Media-Hoarder#62]
Just suggestion but will you consider adding a option to saerch on TMDB for episodes or movies in case missing on imdb or if someone wants to do tmdb orderign for some shows since not all people have full episodes on their disk they only half of an episode especially if its a cartoon or if want to . And not all episodes or movies are on imdb. Like do a link to series or  movie after you scrape from imdb then can link to tmdb for taht show.

Sorry i know primarly from IMDB and no issues so far but just sugestion in-case it happens. SInce not all movies and epiosdes are on IMDB some are on tmdb and vise versa?

**Comment by theMK2k** [comment]
Hi @kolbdog323, yes, we still have this issue open: https://github.com/theMK2k/Media-Hoarder/issues/40

So this is a duplicate and I will close it, will copy the info from here to https://github.com/theMK2k/Media-Hoarder/issues/40.
