### ISSUE TITLE
Bug: Version Checker

### ISSUE THREAD

**Issue by kolbdog323** [theMK2k/Media-Hoarder#67]
Can you please fix that bug since it always shows its up-to-date even when there is a newer release on GitHub since i'm subscribed to the releases and issues but be nice if it says that there is a newer version available when there is one.

**Comment by theMK2k** [comment]
Not really a bug, the version check always checks against the stable release. But I hear you, the beta branch is quite long running and still lots of things to do until we have a stable 1.4.0 release.

**Comment by kolbdog323** [comment]
Maybe add it to the beta release as well for now until the stable version?

**Comment by kolbdog323** [comment]
Sorry just an idea. Its fine if only the stable version. just thought i'd ask. Otherwise keep up good work on this software.

**Comment by theMK2k** [comment]
I'll keep this issue open, maybe I'll find a way so that beta releases can check for new beta versions while stable ones don't.

But the most important thing is: as soon as the beta gets stable it needs to check the stable version updates, else users might miss them which would be really bad ;)

**Comment by theMK2k** [comment]
v1.4.0-b5 is released with your suggestion implemented:

as soon as b6 and later are released and you run b5, it will notify you about those updates in the beta channel, like this:

![image](https://github.com/theMK2k/Media-Hoarder/assets/16878526/63dadfb6-a7cc-4357-b956-91ee852d0226)

The download link in the Version Dialog will also point to the beta releases here on github (and not the Media Hoarder website which only provides downloads for stable releases).

Enjoy!

Download b5 at: <https://github.com/theMK2k/Media-Hoarder/releases/tag/v1.4.0-b>
