### ISSUE TITLE
Suggestion: Add error check for single item rescan

### ISSUE THREAD

**Issue by kolbdog323** [theMK2k/Media-Hoarder#69]
Maybe when you do single item metadata rescan you can implement an automatic error check on the bottom where it shows whats being scanned? So for example you click the rescan metadata then on the bottom where it shows what it's scanning. It can say find -ok, ratings result - okay, companies - okay. Something like that before it goes to the actual re-scanning of the single metadata for the video from imdb.

**Comment by theMK2k** [comment]
You suggest that even before a single item scan a minimalistic imdb scraper check should be performed?

**Comment by kolbdog323** [comment]
Or something similar just in case

**Comment by kolbdog323** [comment]
I'll close this since its a dumb request you can reopen this if you wish to add it to the project. Sorry about that.
