### ISSUE TITLE
Suggestion:  Do part 1 or part 2 after season and episode if have only part of a full episode

### ISSUE THREAD

**Issue by kolbdog323** [theMK2k/Media-Hoarder#74]
I was just thinking that if you have an episode or cartoon but don't have the full episode, and the official episode has a "/" between the episodes on IMDB. You can do this for example "Name of Show - S01E01-part 1" and then for the next part "Name of Show - S01E02-part 2" so that the same episode can be listed twice and the imdb scanner will still detect it, but when it appears on Media Hoarder it can do something like this 1.01-1 for the episode so you know it's just part 1 of a two-part episode or three-part episode, and you can manually edit the plot info yourself to get the correct episode info.

**Comment by kolbdog323** [comment]
I mean so you know its a mult-segment episode not a one or two part episode since some shows esepcially cartoons have multiple segments in a single episode..

**Comment by kolbdog323** [comment]
Just suggestion

**Comment by theMK2k** [comment]
Media Hoarder already has this covered, example:

````
Doctor Who S07E14 1_2 The Name of the Doctor [tt2267346].mkv
Doctor Who S07E14 2_2 The Name of the Doctor [tt2267346].mkv
````

this will be displayed in Media Hoarder as follows:

![image](https://github.com/user-attachments/assets/b9c661b2-9101-46e9-999a-ed583d16927d)

**Comment by kolbdog323** [comment]
Sorry didnt realize that since it wasnt in the readme for handling tv series naming for episodes

**Comment by theMK2k** [comment]
No worries, it is undocumented and I created this for multi-part movies. Had to quickly test it if it works for series episodes, too (which it does).

**Comment by kolbdog323** [comment]
You should probably add it to the episode naming as well in the readme.
